### ISSUE TITLE
Application switcher bug

### ISSUE THREAD

**Issue by fbergo** [raveit65/compiz#3]
system info: fedora 23 (mate+compiz spin), compiz 0.8.12, all updates applied, graphics card nvidia GT 220 with proprietary driver 340.96 (latest).

In the alt+tab switcher, when there are only 2 windows, it skips the other window in the cycle. e.g: If I have window A and window B, and A is active, the graphic on alt+tab shows previews for both A and B but never lands on B.

This behavior does not occur with the shift switcher.

**Comment by soreau** [comment]
Can you specify which switcher plugin it happens with? I'm guessing by 'alt+tab switcher' you're referring to Application Switcher or Static Application Switcher.

**Comment by fbergo** [comment]
It's the Application Switcher.

**Comment by soreau** [comment]
I can't reproduce this problem with Application Switcher in 0.8.12. With only two windows, it switches to both as expected.

**Comment by fbergo** [comment]
video of the issue: https://youtu.be/OmnXIu3e7KQ

if there is any data I can provide to help, let me know. For me the issue occurs with any 2 applications. I do not have the window rules plugin enabled, so no window should be excluded from the taskbar.

**Comment by raveit65** [comment]
@fbergo 
Are you using emerald?
see https://github.com/raveit65/emerald/issues/1
This should be fixed with emerald-0.8.12-2.fc23 (stable repo) or emerald-0.8.12.1-1.fc23
which is in updates testing.
https://bodhi.fedoraproject.org/updates/FEDORA-2016-966f45014b

**Comment by fbergo** [comment]
@raveit65 I'm using the gtk-window-decorator. I switched to emerald (with emerald --replace), the issue persists. I enabled the updates-testing repository and updated to the latest emerald and compiz-plugins-main available there. The issue remain the same, regardless of gtk/emerald being used.

**Comment by soreau** [comment]
It shouldn't matter which decorator you're using, it has to do with the window list ordering. Does it happen without mate-panel running? Also, does it happen with Static Application Switcher?

**Comment by raveit65** [comment]
Ok, i will try to repoduce it with your config in f23.
I'm using nvidia GT 240 with proprietary driver 340.96,  so there shouldn't be a great different to your system.
Normal i use f22.

**Comment by fbergo** [comment]
@soreau: the issue happens with the static application switcher too. It does NOT happen with: ring switcher, shift switcher, stack switcher.

**Comment by fbergo** [comment]
I created a new user account on my system to test the removal of mate-panel (didn't want to mess with my own user config), and before I got to that I found out that the issue does not happen with the default compiz settings, it only happened after I imported the settings from the other account (compiz2016_profile.txt attached above)

any ideas on how to single out what setting is making compiz misbehave ?

**Comment by raveit65** [comment]
well, in the second account you can try to start with default config and then apply step by step your normal settings. You can do that by editing ~.config/compiz/compizconfig/Default.ini by hand (copy/paste the settings for every plugin.
Start 'fusion-icon -n' and you can easily reload compiz after every step.

**Comment by fbergo** [comment]
found it: my configuration had alt-tab assigned to two distinct events in both application switcher and static switcher. 

as_next_key = <Alt>Tab
as_next_all_key = <Alt>Tab

my configuration was imported from a settings file exported from a very old compiz (whichever version I had on my fedora 14 box), so probably the newer compiz didn't react well to something in the old export file.

apologies for the time taken and thanks for the help.
